import type { ClinicStaffRole } from './types';

export const PERMISSIONS: Record<ClinicStaffRole, string[]> = {
  CADMIN: [
    'unit.create',
    'unit.edit',
    'unit.delete',
    'unit.view.all',
    'user.invite',
    'user.edit',
    'user.delete',
    'user.view.all',
    'demand.create',
    'demand.edit',
    'demand.delete',
    'demand.view.all',
    'application.approve',
    'application.reject',
    'application.view.all',
    'marketplace.create',
    'marketplace.edit',
    'marketplace.delete',
    'audit.view',
    'hub.guardians.read',
    'hub.guardians.write',
    'hub.pets.read',
    'hub.pets.write',
    'hub.service_types.read',
    'hub.service_types.write',
    'hub.inventory.read',
    'hub.inventory.write',
    'hub.staff.read',
    'hub.staff.write',
    'hub.staff.invite',
    'hub.appointments.read',
    'hub.appointments.write',
  ],
  CMANAGER: [
    'unit.edit',
    'unit.view',
    'user.invite',
    'user.view',
    'demand.create',
    'demand.edit',
    'demand.delete',
    'demand.view',
    'application.approve',
    'application.reject',
    'application.view',
    'marketplace.create',
    'marketplace.edit',
    'hub.guardians.read',
    'hub.guardians.write',
    'hub.pets.read',
    'hub.pets.write',
    'hub.service_types.read',
    'hub.service_types.write',
    'hub.inventory.read',
    'hub.inventory.write',
    'hub.staff.read',
    'hub.staff.write',
    'hub.staff.invite',
    'hub.appointments.read',
    'hub.appointments.write',
  ],
  CASSISTANT: [
    'unit.view',
    'user.view',
    'demand.create',
    'demand.view',
    'application.view',
    'marketplace.view',
    'hub.guardians.read',
    'hub.pets.read',
    'hub.service_types.read',
    'hub.inventory.read',
    'hub.staff.read',
    'hub.appointments.read',
    'hub.appointments.write',
  ],
  CVET_INTERNAL: [
    'unit.view',
    'demand.view',
    'application.create.internal',
    'application.view.own',
    'hub.inventory.read',
    'hub.staff.read',
    'hub.appointments.read',
  ],
};

export const hasPermission = (role: ClinicStaffRole | null, permission: string): boolean => {
  if (!role) return false;
  const rolePermissions = PERMISSIONS[role];
  return rolePermissions ? rolePermissions.includes(permission) : false;
};
