#!/usr/bin/env python3
"""
Extract only `public` schema DDL + COPY data from a plain-text Supabase / pg_dump
*cluster* SQL file. The full cluster dump cannot be applied to a new Supabase
project (roles, auth, storage, etc. conflict with managed objects).

Usage:
  python3 scripts/extract_public_from_supabase_cluster_dump.py \\
    /path/to/db_cluster-....backup \\
    ./tmp/extracted-public.sql

Important:
  - Prefer creating schema on the NEW project via repo migrations
    (`supabase/migrations/petivet_prod_structure.sql` and/or
    `backend/database_migrations/petimi_vet/STAGING_CONSOLIDATED_MIGRATIONS.sql`,
    then `00_DIAGNOSE_DATABASE.sql` / `01_FIX_ALL_ERRORS.sql` as needed).
  - This dump's DDL may be older than the current app (e.g. legacy column types).
    Treat extracted SQL as a reference or for data-only workflows after review.
  - Auth users live in `auth.users`; restoring them requires a separate process
    (Supabase does not allow re-importing full auth schema from a cluster dump).
"""

from __future__ import annotations

import re
import sys
from pathlib import Path


def main() -> int:
    if len(sys.argv) < 3:
        print(__doc__, file=sys.stderr)
        return 2

    src = Path(sys.argv[1]).expanduser()
    dst = Path(sys.argv[2]).expanduser()
    if not src.is_file():
        print(f"Input not found: {src}", file=sys.stderr)
        return 1

    text = src.read_text(encoding="utf-8", errors="replace")
    text = re.sub(r"^\\restrict\s+\\S+\s*\n", "", text, flags=re.MULTILINE)

    sections = re.split(r"\n(?=--\n-- Name:)", text)

    out: list[str] = [
        "-- Generated by extract_public_from_supabase_cluster_dump.py\n"
        "-- Review and edit before running on Supabase.\n"
        "SET client_encoding = 'UTF8';\n"
        "SET standard_conforming_strings = on;\n\n"
    ]

    kept = 0
    for part in sections:
        part = part.strip()
        if not part.startswith("--"):
            continue
        lines = part.split("\n")
        # Expect: "--", "-- Name: …; Type: …; Schema: …; Owner: …", "--"
        name_line = ""
        if len(lines) >= 2 and lines[0].strip() == "--":
            name_line = lines[1]
        if "; Schema: public;" not in name_line:
            continue
        out.append(part + "\n\n")
        kept += 1

    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text("".join(out), encoding="utf-8")
    print(f"Wrote {dst} ({kept} public object sections).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
